-- ---------------------------------------------------
-- Forum tables
-- ---------------------------------------------------
CREATE TABLE threads(
    id INT UNSIGNED AUTO_INCREMENT,
    user_id INT,
    topic VARCHAR(30) NOT NULL,
    content TEXT NOT NULL,
    created DATETIME DEFAULT NULL,
    modified DATETIME DEFAULT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE posts(
    id INT UNSIGNED AUTO_INCREMENT,
    user_id INT NOT NULL,
    thread_id INT NOT NULL,
    content TEXT NOT NULL,
    created DATETIME DEFAULT NULL,
    modified DATETIME DEFAULT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(user_id) REFERENCES users(id),
    FOREIGN KEY(thread_id) REFERENCES thread(id)
);


-- ---------------------------------------------------
-- User tables
-- ---------------------------------------------------
CREATE TABLE `groups` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(100) NOT NULL,
    `created` datetime DEFAULT NULL,
    PRIMARY KEY (`id`)
);

CREATE TABLE `users` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `username` varchar(50) NOT NULL,
    `password` char(40) NOT NULL,
    `group_id` int(11) NOT NULL,
    `created` datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `username` (`username`),
    FOREIGN KEY(`group_id`) REFERENCES groups(`id`)
);


-- ---------------------------------------------------
-- Registration tables
-- ---------------------------------------------------
CREATE TABLE `register_keys` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `user_id` int(11) NOT NULL,
    `comment` text,
    `key` char(19) NOT NULL,
    `group_id` int(11) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `key` (`key`),
    FOREIGN KEY(`user_id`) REFERENCES users(`id`),
    FOREIGN KEY(`group_id`) REFERENCES groups(`id`)
);


-- ---------------------------------------------------
-- Acl tables - Generated by CakePHP, don't change
-- ---------------------------------------------------
CREATE TABLE `acos` (
    `id` int(10) NOT NULL AUTO_INCREMENT,
    `parent_id` int(10) DEFAULT NULL,
    `model` varchar(255) DEFAULT NULL,
    `foreign_key` int(10) DEFAULT NULL,
    `alias` varchar(255) DEFAULT NULL,
    `lft` int(10) DEFAULT NULL,
    `rght` int(10) DEFAULT NULL,
    PRIMARY KEY (`id`)
);

CREATE TABLE `aros` (
    `id` int(10) NOT NULL AUTO_INCREMENT,
    `parent_id` int(10) DEFAULT NULL,
    `model` varchar(255) DEFAULT NULL,
    `foreign_key` int(10) DEFAULT NULL,
    `alias` varchar(255) DEFAULT NULL,
    `lft` int(10) DEFAULT NULL,
    `rght` int(10) DEFAULT NULL,
    PRIMARY KEY (`id`)
);

CREATE TABLE `aros_acos` (
    `id` int(10) NOT NULL AUTO_INCREMENT,
    `aro_id` int(10) NOT NULL,
    `aco_id` int(10) NOT NULL,
    `_create` varchar(2) NOT NULL DEFAULT '0',
    `_read` varchar(2) NOT NULL DEFAULT '0',
    `_update` varchar(2) NOT NULL DEFAULT '0',
    `_delete` varchar(2) NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `ARO_ACO_KEY` (`aro_id`,`aco_id`)
);
