CREATE TABLE users(
id INT UNSIGNED AUTO_INCREMENT,
user_id INT NOT NULL,
email VARCHAR(30),
password VARCHAR(30),
salt VARCHAR(30),
created DATETIME DEFAULT NULL,
modified DATETIME DEFAULT NULL,
PRIMARY KEY(id)

);

CREATE TABLE threads(
id INT UNSIGNED AUTO_INCREMENT,
user_id INT,
topic VARCHAR(30) NOT NULL,
content TEXT NOT NULL,
created DATETIME DEFAULT NULL,
modified DATETIME DEFAULT NULL,
PRIMARY KEY(id),
FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE inlays(
id INT UNSIGNED AUTO_INCREMENT,
user_id INT NOT NULL,
thread_id INT NOT NULL,
content TEXT NOT NULL,
created DATETIME DEFAULT NULL,
modified DATETIME DEFAULT NULL,
PRIMARY KEY(id),
FOREIGN KEY(user_id) REFERENCES users(id),
FOREIGN KEY(thread_id) REFERENCES thread(id)
);